### ISSUE TITLE
Check All for Fields

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/modulebuilder#26]
We need to add to the fields setup a "Check All" checkbox, similar to what we have in the module view:

![image](https://user-images.githubusercontent.com/613686/82980536-b142d480-9fb7-11ea-9580-63e329915721.png)

Right now there are to many check boxes to click for each field :( 

![image](https://user-images.githubusercontent.com/613686/82980595-d59eb100-9fb7-11ea-9452-4d2d25d487a5.png)

**Comment by ggoffy** [comment]
here I'm will try to find another solution, because checking all is not foreseen:
`User index: in header / User index: in body / User index: in footer`
and
`User file: in header / User index: in body / User index: in footer`
will only be used, if 'User: In Files' is checked

the next is: you shouldn't display a value in header, body and footer in the same time

all these 'inconsistences' will be checked and shown when you click on button 'Run data check...' on building tab

**Comment by mambax7** [comment]
It was more issue of speed. There are 14 checkboxes - if I have to check only 3, then it's faster to do it manually. 
But if I have to check 10, then it's faster to "check all" and then manually "uncheck" the 4 that I don't need. 
It's simply giving the developer a chance to do something faster...
