### ISSUE TITLE
Block problem

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/modulebuilder#76]
There are five blocks in the created module .
- Block Top
- Block Random
- Block Hits
- Block New
- Block Last

but only the last added block works.

These blocks don't work :
- Block Top
- Block Random
- Block Hits
- Block New

When I activate the block, the following error occurs 
![d1](https://user-images.githubusercontent.com/5504159/106292938-7be53980-625e-11eb-959f-d98dc9a3c83e.jpg)

**Comment by ggoffy** [comment]
hi.
the problem is that you need for this blocks specific data, e.g. for newest one you need a date field where you store the date of creation. As I / modulebuilder do not know in advance, how you name your field modulebuilder takes an example. if you use test data it will use "art_created" in the block. the same for top or hits, you need a corresponding data field.
![grafik](https://user-images.githubusercontent.com/7547661/106389682-e6c07d00-63e4-11eb-9566-784efc356e24.png)

**Comment by ggoffy** [comment]
hi. 

block new: the date problem is fixed.

block random: is working as it should, as far as I see.

for blocks "top" and "hits":
I / modulebuilder do not know how you define "top" or "hits" and what names the field with the necessary data have.
Therefore modulebuilder takes and example name (e.g. "art_hits"). you must decide yourself how you define the necessary fields and adapt then the code lines.

**Comment by Heyula** [comment]
Hi;
I will create a new module and report the results.

**Comment by Heyula** [comment]
Hi ggoffy;
All blocks are now working.
Thank you so much.

![1](https://user-images.githubusercontent.com/5504159/106618950-1c9a6880-6581-11eb-83a1-d3be8f533b9e.jpg)
![2](https://user-images.githubusercontent.com/5504159/106618955-1dcb9580-6581-11eb-93c6-2241de1e584d.jpg)

**Comment by ggoffy** [comment]
Thank you for feedback
